import type { Metadata } from "next";
import { Arizonia } from "next/font/google";
import "./globals.css";

const arizonia = Arizonia<"--font-arizonia">({
  variable: "--font-arizonia",
  subsets: ["vietnamese"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arizonia.variable}  antialiased`}>{children}</body>
    </html>
  );
}
